#
# board/somlabs/visionsom-x2l/Makefile
#
# Copyright (C) 2023 Somlabs
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y	:= ../../renesas/rcar-common/gen3-spl.o
else
obj-y	:= visionsom-x2l.o ../../renesas/rcar-common/common.o
endif
